import forms from "@tailwindcss/forms";
import { createThemes } from "tw-colors";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.tsx",
        "./resources/js/**/*.ts",
    ],
    theme: {
        screens: {
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1224px",
        },
        container: {
            center: true,
            padding: {
                DEFAULT: "1rem",
                sm: "2rem",
                lg: "4rem",
                xl: "0px",
            },
        },
        fontFamily: {
            roboto: ["Roboto"],
            lato: ["Lato"],
            sora: ["Sora"],
            poppins: ["Poppins"],
            raleway: ["Raleway"],
            oswlad: ["Oswald"],
            anton: ["Anton"],
            archivo: ["Archivo"],
            epilogue: ["Epilogue"],
            san: ["Montserrat Alternates", "Encode Sans", "Work Sans"],
            tiro_bangla: "Tiro Bangla",
            serif: [
                "Lora",
                "Andada Pro",
                "Hahmlet",
                "Cormorant",
                "Old Standard TT",
                "Playfair Display",
                "Anton",
                "Archivo",
            ],
            monospace: ["JetBrains Mono", "Source Code Pro"],
            bangla_uni: ["Noto Serif Bengali", "Baloo Da 2"],
            galada: ["Galada"],
            mrs_saint_delafield: ["Mrs Saint Delafield"],
            amita: ["Amita"],
            cookie: ["Cookie"],
            rock_salt: ["Rock Salt"],
            sacramento: ["Sacramento"],
            hurricane: ["Hurricane"],
            stalemate: ["Stalemate"],
            ms_madi: ["Ms Madi"],
            kolker: ["Kolker Brush"],
        },
    },
    plugins: [
        forms,
        require("@tailwindcss/typography"),
        createThemes(
            {
                light: {
                    primary: "#222d67",
                    onPrimary: "#f3f3f3",
                    primaryVariant: "#162742",
                    onPrimaryVariant: "#f3f3f3",
                    secondary: "#8f407b",
                    onSecondary: "#fdf1ed",
                    secondaryVariant: "#2b2b2b",
                    onSecondaryVariant: "#777c79",
                    background: "#f5f7f8",
                    onBackground: "#3f3f3f",
                    surface: "#ffffff",
                    onSurface: "#3b3b3b",
                    error: "#b12e06",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                    disabled: "#777c79",
                    onDisabled: "#131313",
                    borderColor: "#ebebeb",
                },
                dark: {
                    primary: "#9c662a",
                    onPrimary: "#f3f3f3",
                    primaryVariant: "#734a1c",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#29271e",
                    onBackground: "#eeeee2",
                    surface: "#313534",
                    onSurface: "#8b8c8b",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                    disabled: "#777c79",
                    onDisabled: "#131313",
                    borderColor: "#4a4a4a",
                },
                halloween: {
                    primary: "#252359",
                    onPrimary: "#777c79",
                    primaryVariant: "orange",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#29271e",
                    onBackground: "#777c79",
                    surface: "#313534",
                    onSurface: "#777c79",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                    disabled: "#777c79",
                    onDisabled: "#131313",
                    borderColor: "#3b3b3b",
                },
                summer: {
                    primary: "#252359",
                    onPrimary: "#777c79",
                    primaryVariant: "orange",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#29271e",
                    onBackground: "#777c79",
                    surface: "#313534",
                    onSurface: "#777c79",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                    disabled: "#777c79",
                    onDisabled: "#131313",
                    borderColor: "#3b3b3b",
                },
                winter: {
                    primary: "#252359",
                    onPrimary: "#777c79",
                    primaryVariant: "orange",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#29271e",
                    onBackground: "#777c79",
                    surface: "#313534",
                    onSurface: "#777c79",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                    disabled: "#777c79",
                    onDisabled: "#131313",
                    borderColor: "#3b3b3b",
                },
                party: {
                    primary: "#252359",
                    onPrimary: "#777c79",
                    primaryVariant: "orange",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#676e66",
                    onBackground: "#777c79",
                    surface: "#313534",
                    onSurface: "#777c79",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                    disabled: "#777c79",
                    onDisabled: "#131313",
                    borderColor: "#3b3b3b",
                },
            },
            {
                defaultTheme: "light",
            }
        ),
    ],
};
