import forms from "@tailwindcss/forms";
import { createThemes } from "tw-colors";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.tsx",
        "./resources/js/**/*.ts",
    ],
    plugins: [
        forms,
        createThemes(
            {
                light: {
                    primary: "#222d67",
                    onPrimary: "#f3f3f3",
                    primaryVariant: "#162742",
                    onPrimaryVariant: "#f3f3f3",
                    secondary: "#8f407b",
                    onSecondary: "#fdf1ed",
                    secondaryVariant: "#2b2b2b",
                    onSecondaryVariant: "#777c79",
                    background: "#eeeee8",
                    onBackground: "#3f3f3f",
                    surface: "#ffffff",
                    onSurface: "#3b3b3b",
                    error: "#b12e06",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                },
                dark: {
                    primary: "#252359",
                    onPrimary: "#777c79",
                    primaryVariant: "orange",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#29271e",
                    onBackground: "#777c79",
                    surface: "#313534",
                    onSurface: "#777c79",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                },
                halloween: {
                    primary: "#252359",
                    onPrimary: "#777c79",
                    primaryVariant: "orange",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#29271e",
                    onBackground: "#777c79",
                    surface: "#313534",
                    onSurface: "#777c79",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                },
                summer: {
                    primary: "#252359",
                    onPrimary: "#777c79",
                    primaryVariant: "orange",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#29271e",
                    onBackground: "#777c79",
                    surface: "#313534",
                    onSurface: "#777c79",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                },
                winter: {
                    primary: "#252359",
                    onPrimary: "#777c79",
                    primaryVariant: "orange",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#29271e",
                    onBackground: "#777c79",
                    surface: "#313534",
                    onSurface: "#777c79",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                },
                party: {
                    primary: "#252359",
                    onPrimary: "#777c79",
                    primaryVariant: "orange",
                    onPrimaryVariant: "#777c79",
                    secondary: "#4D4D45",
                    onSecondary: "#777c79",
                    secondaryVariant: "yellow",
                    onSecondaryVariant: "#777c79",
                    background: "#676e66",
                    onBackground: "#777c79",
                    surface: "#313534",
                    onSurface: "#777c79",
                    error: "orange",
                    onError: "#777c79",
                    brand: "#182372",
                    onBrand: "#777c79",
                },
            },
            {
                defaultTheme: "light",
            }
        ),
    ],
};
